"use client";
import { ReactNode,useState } from "react";
import { Box,Drawer,List,ListItemButton,ListItemIcon,ListItemText,Divider,Button } from "@mui/material";
import Link from "next/link";
import Sidebar from "./Sidebar";
import Header from "./Header";
import DashboardIcon from "@mui/icons-material/Dashboard";import ApartmentIcon from "@mui/icons-material/Apartment";import MeetingRoomIcon from "@mui/icons-material/MeetingRoom";import PeopleIcon from "@mui/icons-material/People";import PaymentsIcon from "@mui/icons-material/Payments";import ReceiptLongIcon from "@mui/icons-material/ReceiptLong";import AssessmentIcon from "@mui/icons-material/Assessment";import NotificationsIcon from "@mui/icons-material/Notifications";import SettingsIcon from "@mui/icons-material/Settings";import LogoutIcon from "@mui/icons-material/Logout";import {signOut} from "next-auth/react";
const items=[["/dashboard","Dashboard",DashboardIcon],["/pgs","PGs",ApartmentIcon],["/rooms","Rooms",MeetingRoomIcon],["/students","Students",PeopleIcon],["/payments","Payments",PaymentsIcon],["/billing","Monthly Billing",ReceiptLongIcon],["/expenses","Expenses",ReceiptLongIcon],["/reports","Reports",AssessmentIcon],["/reminders","Reminders",NotificationsIcon],["/settings","Settings",SettingsIcon]] as const;
export default function Layout({children}:{children:ReactNode}){const[open,setOpen]=useState(false);return <Box sx={{display:"flex",minHeight:"100vh"}}><Sidebar open={open} onClose={()=>setOpen(false)}/><Drawer open={open} onClose={()=>setOpen(false)} sx={{display:{md:"none"},"& .MuiDrawer-paper":{width:270}}}><Box sx={{p:2,fontWeight:800}}>PG Manager</Box><Divider/><List>{items.map(([h,l,I])=><ListItemButton component={Link} href={h} onClick={()=>setOpen(false)} key={h}><ListItemIcon><I/></ListItemIcon><ListItemText primary={l}/></ListItemButton>)}</List><Button startIcon={<LogoutIcon/>} onClick={()=>signOut({callbackUrl:"/login"})}>Logout</Button></Drawer><Box sx={{flex:1,minWidth:0}}><Header onMenu={()=>setOpen(true)}/><Box component="main" sx={{p:{xs:2,md:3}}}>{children}</Box></Box></Box>}
